ITEM = {'id': 'surplus_fons',
 'name': '方斯',
 'cost': 0,
 'power': 1,
 'type': 'anomaly_item',
 'element': '异象',
 'rarity': 'r',
 'art': '/static/images/item/方斯.webp',
 'description': '无效果。',
 'effect_key': '',
 'tags': ['surplus', 'tool', 'material', 'mat_coin'],
 'archetype': 'surplus',
 'category': '货币',
 'attribute': '光',
 'attribute_icon': '/static/images/elements/光.png',
 'material_tags': ['mat_coin'],
 'material_cost': None,
 'required_material_attribute': '',
 'material_requirements': [],
 'material_requirement_text': '',
 'target_rule': {},
 'icon': '/static/images/item/方斯.webp'}
