GAME_MAP = {
    'id': 'lower_relay_district',
    'name': 'Lower Relay District',
    'width': 8,
    'height': 6,
    'current_layer': 1,
    'total_layers': 3,
    'background_image': '/static/images/maps/lower_relay_district_abandoned_city.png',
    'start': {'x': 0, 'y': 0},
    'tiles': [
        # Layer 1: relay entrance.
        {'layer': 1, 'x': 2, 'y': 0, 'type': 'turn_belt', 'object_id': 'turn_belt', 'direction': 'down'},
        {'layer': 1, 'x': 5, 'y': 1, 'type': 'portal', 'object_id': 'portal', 'target': {'layer': 2, 'x': 0, 'y': 0}},
        {'layer': 1, 'x': 2, 'y': 2, 'type': 'chest', 'object_id': 'chest', 'loot_table': ['heal', 'attack', 'key']},
        {'layer': 1, 'x': 4, 'y': 2, 'type': 'event', 'object_id': 'event_shrine', 'event_kind': 'shrine'},
        {'layer': 1, 'x': 1, 'y': 3, 'type': 'turn_belt', 'object_id': 'turn_belt', 'direction': 'right'},
        {'layer': 1, 'x': 3, 'y': 3, 'type': 'door', 'object_id': 'door', 'locked': True},
        {'layer': 1, 'x': 2, 'y': 4, 'type': 'event', 'object_id': 'event_forge', 'event_kind': 'forge'},
        {'layer': 1, 'x': 1, 'y': 1, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 1, 'x': 6, 'y': 0, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 1, 'x': 0, 'y': 2, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 1, 'x': 6, 'y': 2, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 1, 'x': 4, 'y': 3, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 1, 'x': 7, 'y': 3, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 1, 'x': 6, 'y': 5, 'type': 'wall', 'object_id': 'wall'},

        # Layer 2: middle relay maze.
        {'layer': 2, 'x': 0, 'y': 0, 'type': 'portal', 'object_id': 'portal', 'target': {'layer': 1, 'x': 5, 'y': 1}},
        {'layer': 2, 'x': 6, 'y': 4, 'type': 'portal', 'object_id': 'portal', 'target': {'layer': 3, 'x': 0, 'y': 0}},
        {'layer': 2, 'x': 3, 'y': 0, 'type': 'turn_belt', 'object_id': 'turn_belt', 'direction': 'down'},
        {'layer': 2, 'x': 5, 'y': 2, 'type': 'chest', 'object_id': 'chest', 'loot_table': ['heal', 'attack', 'key']},
        {'layer': 2, 'x': 1, 'y': 4, 'type': 'event', 'object_id': 'event_shrine', 'event_kind': 'shrine'},
        {'layer': 2, 'x': 4, 'y': 4, 'type': 'event', 'object_id': 'event_forge', 'event_kind': 'forge'},
        {'layer': 2, 'x': 2, 'y': 1, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 2, 'x': 4, 'y': 1, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 2, 'x': 7, 'y': 1, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 2, 'x': 0, 'y': 2, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 2, 'x': 2, 'y': 3, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 2, 'x': 3, 'y': 3, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 2, 'x': 7, 'y': 4, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 2, 'x': 2, 'y': 5, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 2, 'x': 5, 'y': 5, 'type': 'wall', 'object_id': 'wall'},

        # Layer 3: boss arena.
        {'layer': 3, 'x': 0, 'y': 0, 'type': 'portal', 'object_id': 'portal', 'target': {'layer': 2, 'x': 6, 'y': 4}},
        {'layer': 3, 'x': 1, 'y': 1, 'type': 'chest', 'object_id': 'chest', 'loot_table': ['heal', 'attack', 'key']},
        {'layer': 3, 'x': 3, 'y': 1, 'type': 'event', 'object_id': 'event_shrine', 'event_kind': 'shrine'},
        {'layer': 3, 'x': 5, 'y': 4, 'type': 'boss_tile', 'object_id': 'boss_tile'},
        {'layer': 3, 'x': 6, 'y': 4, 'type': 'boss_tile', 'object_id': 'boss_tile'},
        {'layer': 3, 'x': 5, 'y': 5, 'type': 'boss_tile', 'object_id': 'boss_tile'},
        {'layer': 3, 'x': 6, 'y': 5, 'type': 'boss_tile', 'object_id': 'boss_tile'},
        {'layer': 3, 'x': 2, 'y': 0, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 3, 'x': 4, 'y': 0, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 3, 'x': 6, 'y': 1, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 3, 'x': 1, 'y': 2, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 3, 'x': 4, 'y': 2, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 3, 'x': 7, 'y': 2, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 3, 'x': 2, 'y': 3, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 3, 'x': 0, 'y': 5, 'type': 'wall', 'object_id': 'wall'},
        {'layer': 3, 'x': 3, 'y': 5, 'type': 'wall', 'object_id': 'wall'},
    ],
    'monsters': [
        {'layer': 1, 'id': 'sweeper_alpha', 'name': 'Sweeper Alpha', 'x': 3, 'y': 1, 'max_hp': 18, 'hp': 18, 'attack': 8, 'defense': 2, 'range': 1, 'kind': 'monster'},
        {'layer': 1, 'id': 'watcher_beta', 'name': 'Watcher Beta', 'x': 1, 'y': 4, 'max_hp': 16, 'hp': 16, 'attack': 7, 'defense': 1, 'range': 2, 'kind': 'monster'},
        {'layer': 2, 'id': 'relay_hunter', 'name': 'Relay Hunter', 'x': 4, 'y': 2, 'max_hp': 20, 'hp': 20, 'attack': 9, 'defense': 2, 'range': 2, 'kind': 'monster'},
        {'layer': 2, 'id': 'gatekeeper_delta', 'name': 'Gatekeeper Delta', 'x': 6, 'y': 2, 'max_hp': 22, 'hp': 22, 'attack': 10, 'defense': 3, 'range': 1, 'kind': 'monster'},
        {'layer': 3, 'id': 'crusher_gamma', 'name': 'Crusher Gamma', 'x': 4, 'y': 4, 'max_hp': 24, 'hp': 24, 'attack': 10, 'defense': 3, 'range': 1, 'kind': 'monster'},
        {'layer': 3, 'id': 'core_guard', 'name': 'Core Guard', 'x': 3, 'y': 3, 'max_hp': 26, 'hp': 26, 'attack': 11, 'defense': 3, 'range': 1, 'kind': 'monster'},
    ],
    'boss': {
        'id': 'abyss_core',
        'name': 'Abyss Core',
        'positions': [
            {'layer': 3, 'x': 5, 'y': 4},
            {'layer': 3, 'x': 6, 'y': 4},
            {'layer': 3, 'x': 5, 'y': 5},
            {'layer': 3, 'x': 6, 'y': 5},
        ],
        'max_hp': 60,
        'hp': 60,
        'attack': 12,
        'defense': 4,
        'range': 1,
        'kind': 'boss',
    },
}
