from __future__ import annotations

from typing import Any

JsonDict = dict[str, Any]

GENESIS_ITEM_IDS = ['genesis_urban_energy',
 'genesis_urban_energy',
 'genesis_urban_energy',
 'genesis_refresh_charge',
 'genesis_refresh_charge',
 'genesis_refresh_charge',
 'genesis_breakfast_bag',
 'genesis_breakfast_bag',
 'genesis_breakfast_bag',
 'genesis_marble_soda',
 'genesis_marble_soda',
 'genesis_eborn_cake',
 'genesis_eborn_cake',
 'genesis_eborn_cake',
 'genesis_chip_washer',
 'genesis_chip_washer',
 'genesis_nest_shard',
 'genesis_nest_shard',
 'genesis_muscle_faith',
 'genesis_muscle_faith']

DELAY_ITEM_IDS = ['delay_first_wish',
 'delay_first_wish',
 'delay_first_wish',
 'delay_mind_sync',
 'delay_mind_sync',
 'delay_mind_sync',
 'delay_water_hesitation',
 'delay_water_hesitation',
 'delay_water_hesitation',
 'delay_recruit_fear',
 'delay_recruit_fear',
 'delay_recruit_fear',
 'delay_nestling_hope',
 'delay_nestling_hope',
 'delay_commute_bag',
 'delay_commute_bag',
 'delay_missed_call',
 'delay_missed_call',
 'delay_kaleidoscope',
 'delay_kaleidoscope']

MURK_ITEM_IDS = ['murk_basic_material_box',
 'murk_basic_material_box',
 'murk_basic_material_box',
 'murk_lost_whisper',
 'murk_lost_whisper',
 'murk_lost_whisper',
 'murk_faded_shadow',
 'murk_faded_shadow',
 'murk_faded_shadow',
 'murk_blur_number',
 'murk_blur_number',
 'murk_blur_number',
 'murk_fantasy_delusion',
 'murk_fantasy_delusion',
 'murk_knight_spark',
 'murk_knight_spark',
 'murk_other_side_page',
 'murk_other_side_page',
 'murk_colorful_ticket',
 'murk_colorful_ticket']

DARKSTAR_ITEM_IDS = ['darkstar_mining_permit',
 'darkstar_mining_permit',
 'darkstar_mining_permit',
 'darkstar_ringstone',
 'darkstar_ringstone',
 'darkstar_ringstone',
 'darkstar_nature_pixel',
 'darkstar_nature_pixel',
 'darkstar_nature_pixel',
 'darkstar_denoise_base',
 'darkstar_denoise_base',
 'darkstar_oracle_stone',
 'darkstar_oracle_stone',
 'darkstar_oracle_stone',
 'darkstar_listening_crystal',
 'darkstar_listening_crystal',
 'darkstar_dream_knot',
 'darkstar_dream_knot',
 'darkstar_someone_helmet',
 'darkstar_someone_helmet']

SURPLUS_ITEM_IDS = ['genesis_urban_energy',
 'genesis_urban_energy',
 'genesis_refresh_charge',
 'genesis_refresh_charge',
 'genesis_breakfast_bag',
 'genesis_breakfast_bag',
 'genesis_marble_soda',
 'genesis_eborn_cake',
 'genesis_chip_washer',
 'genesis_nest_shard',
 'delay_first_wish',
 'delay_first_wish',
 'delay_mind_sync',
 'delay_mind_sync',
 'delay_water_hesitation',
 'delay_water_hesitation',
 'delay_recruit_fear',
 'delay_commute_bag',
 'surplus_fons',
 'surplus_a_coin']

DISCORD_ITEM_IDS = ['murk_basic_material_box',
 'murk_basic_material_box',
 'murk_lost_whisper',
 'murk_lost_whisper',
 'murk_faded_shadow',
 'murk_faded_shadow',
 'murk_blur_number',
 'murk_fantasy_delusion',
 'murk_knight_spark',
 'darkstar_mining_permit',
 'darkstar_mining_permit',
 'darkstar_ringstone',
 'darkstar_ringstone',
 'darkstar_nature_pixel',
 'darkstar_oracle_stone',
 'darkstar_listening_crystal',
 'darkstar_someone_helmet',
 'discord_tomato',
 'discord_tomato_100',
 'discord_tomato_bucket']

DUEL_DECKS: list[JsonDict] = [{'id': 'genesis_bloom',
  'name': '创生养成',
  'short_name': '创生',
  'description': '加身材、养大怪，用创生保护素材和异能者不被小伤害刮死。',
  'difficulty': '新手推荐',
  'ai_nickname': '创生试炼 AI',
  'card_ids': ['genesis_urban_energy',
               'genesis_urban_energy',
               'genesis_urban_energy',
               'genesis_refresh_charge',
               'genesis_refresh_charge',
               'genesis_refresh_charge',
               'genesis_breakfast_bag',
               'genesis_breakfast_bag',
               'genesis_breakfast_bag',
               'genesis_marble_soda',
               'genesis_marble_soda',
               'genesis_eborn_cake',
               'genesis_eborn_cake',
               'genesis_eborn_cake',
               'genesis_chip_washer',
               'genesis_chip_washer',
               'genesis_nest_shard',
               'genesis_nest_shard',
               'genesis_muscle_faith',
               'genesis_muscle_faith'],
  'esper_card_ids': ['nanali', 'bohe', 'xun', 'jiuyuan'],
  'ai_plan': {'priority_card_ids': ['genesis_urban_energy',
                                    'genesis_urban_energy',
                                    'genesis_urban_energy',
                                    'genesis_refresh_charge',
                                    'genesis_refresh_charge',
                                    'genesis_refresh_charge',
                                    'genesis_breakfast_bag',
                                    'genesis_breakfast_bag',
                                    'genesis_breakfast_bag',
                                    'genesis_marble_soda',
                                    'genesis_marble_soda',
                                    'genesis_eborn_cake',
                                    'genesis_eborn_cake',
                                    'genesis_eborn_cake',
                                    'genesis_chip_washer',
                                    'genesis_chip_washer',
                                    'genesis_nest_shard',
                                    'genesis_nest_shard',
                                    'genesis_muscle_faith',
                                    'genesis_muscle_faith'],
              'esper_priority_ids': ['nanali', 'bohe', 'xun', 'jiuyuan']}},
 {'id': 'delay_lock',
  'name': '延滞锁控',
  'short_name': '延滞',
  'description': '拖延对手行动，用控制型异能者真正封住关键素材与登场窗口。',
  'difficulty': '资源规划',
  'ai_nickname': '延滞锁控 AI',
  'card_ids': ['delay_first_wish',
               'delay_first_wish',
               'delay_first_wish',
               'delay_mind_sync',
               'delay_mind_sync',
               'delay_mind_sync',
               'delay_water_hesitation',
               'delay_water_hesitation',
               'delay_water_hesitation',
               'delay_recruit_fear',
               'delay_recruit_fear',
               'delay_recruit_fear',
               'delay_nestling_hope',
               'delay_nestling_hope',
               'delay_commute_bag',
               'delay_commute_bag',
               'delay_missed_call',
               'delay_missed_call',
               'delay_kaleidoscope',
               'delay_kaleidoscope'],
  'esper_card_ids': ['hasuoer', 'yi', 'protagonist', 'chaos'],
  'ai_plan': {'priority_card_ids': ['delay_first_wish',
                                    'delay_first_wish',
                                    'delay_first_wish',
                                    'delay_mind_sync',
                                    'delay_mind_sync',
                                    'delay_mind_sync',
                                    'delay_water_hesitation',
                                    'delay_water_hesitation',
                                    'delay_water_hesitation',
                                    'delay_recruit_fear',
                                    'delay_recruit_fear',
                                    'delay_recruit_fear',
                                    'delay_nestling_hope',
                                    'delay_nestling_hope',
                                    'delay_commute_bag',
                                    'delay_commute_bag',
                                    'delay_missed_call',
                                    'delay_missed_call',
                                    'delay_kaleidoscope',
                                    'delay_kaleidoscope'],
              'esper_priority_ids': ['hasuoer', 'yi', 'protagonist', 'chaos']}},
 {'id': 'murk_burn',
  'name': '浊燃节奏',
  'short_name': '浊燃',
  'description': '用持续压制建立优势，打掉素材并在中期滚出节奏差。',
  'difficulty': '节奏压制',
  'ai_nickname': '浊燃节奏 AI',
  'card_ids': ['murk_basic_material_box',
               'murk_basic_material_box',
               'murk_basic_material_box',
               'murk_lost_whisper',
               'murk_lost_whisper',
               'murk_lost_whisper',
               'murk_faded_shadow',
               'murk_faded_shadow',
               'murk_faded_shadow',
               'murk_blur_number',
               'murk_blur_number',
               'murk_blur_number',
               'murk_fantasy_delusion',
               'murk_fantasy_delusion',
               'murk_knight_spark',
               'murk_knight_spark',
               'murk_other_side_page',
               'murk_other_side_page',
               'murk_colorful_ticket',
               'murk_colorful_ticket'],
  'esper_card_ids': ['adler', 'zaowu', 'requiem', 'baicang'],
  'ai_plan': {'priority_card_ids': ['murk_lost_whisper',
                                    'murk_faded_shadow',
                                    'murk_blur_number',
                                    'murk_basic_material_box',
                                    'murk_fantasy_delusion',
                                    'murk_knight_spark',
                                    'murk_other_side_page',
                                    'murk_colorful_ticket'],
              'esper_priority_ids': ['adler', 'zaowu', 'requiem', 'baicang']}},
 {'id': 'darkstar_bomb',
  'name': '黯星爆返',
  'short_name': '黯星',
  'description': '前期蓄能偏弱，后期依靠黯星引爆一波返场。',
  'difficulty': '爆发反打',
  'ai_nickname': '黯星爆返 AI',
  'card_ids': ['darkstar_mining_permit',
               'darkstar_mining_permit',
               'darkstar_mining_permit',
               'darkstar_ringstone',
               'darkstar_ringstone',
               'darkstar_ringstone',
               'darkstar_nature_pixel',
               'darkstar_nature_pixel',
               'darkstar_nature_pixel',
               'darkstar_denoise_base',
               'darkstar_denoise_base',
               'darkstar_oracle_stone',
               'darkstar_oracle_stone',
               'darkstar_oracle_stone',
               'darkstar_listening_crystal',
               'darkstar_listening_crystal',
               'darkstar_dream_knot',
               'darkstar_dream_knot',
               'darkstar_someone_helmet',
               'darkstar_someone_helmet'],
  'esper_card_ids': ['fatiya', 'haniya', 'haiyue', 'dafutier'],
  'ai_plan': {'priority_card_ids': ['darkstar_mining_permit',
                                    'darkstar_mining_permit',
                                    'darkstar_mining_permit',
                                    'darkstar_ringstone',
                                    'darkstar_ringstone',
                                    'darkstar_ringstone',
                                    'darkstar_nature_pixel',
                                    'darkstar_nature_pixel',
                                    'darkstar_nature_pixel',
                                    'darkstar_denoise_base',
                                    'darkstar_denoise_base',
                                    'darkstar_oracle_stone',
                                    'darkstar_oracle_stone',
                                    'darkstar_oracle_stone',
                                    'darkstar_listening_crystal',
                                    'darkstar_listening_crystal',
                                    'darkstar_dream_knot',
                                    'darkstar_dream_knot',
                                    'darkstar_someone_helmet',
                                    'darkstar_someone_helmet'],
              'esper_priority_ids': ['fatiya', 'haniya', 'haiyue', 'dafutier']}},
 {'id': 'surplus_combo',
  'name': '盈蓄费用魔术',
  'short_name': '盈蓄',
  'description': '创生与延滞的进阶复合，用费用魔术大量出牌，并靠延滞拖慢对手。',
  'difficulty': '高阶展开',
  'ai_nickname': '盈蓄连锁 AI',
  'card_ids': ['genesis_urban_energy',
               'genesis_urban_energy',
               'genesis_refresh_charge',
               'genesis_refresh_charge',
               'genesis_breakfast_bag',
               'genesis_breakfast_bag',
               'genesis_marble_soda',
               'genesis_eborn_cake',
               'genesis_chip_washer',
               'genesis_nest_shard',
               'delay_first_wish',
               'delay_first_wish',
               'delay_mind_sync',
               'delay_mind_sync',
               'delay_water_hesitation',
               'delay_water_hesitation',
               'delay_recruit_fear',
               'delay_commute_bag',
               'surplus_fons',
               'surplus_a_coin'],
  'esper_card_ids': ['xiaozhi', 'edgar', 'nanali', 'hasuoer'],
  'ai_plan': {'priority_card_ids': ['genesis_urban_energy',
                                    'genesis_urban_energy',
                                    'genesis_refresh_charge',
                                    'genesis_refresh_charge',
                                    'genesis_breakfast_bag',
                                    'genesis_breakfast_bag',
                                    'genesis_marble_soda',
                                    'genesis_eborn_cake',
                                    'genesis_chip_washer',
                                    'genesis_nest_shard',
                                    'delay_first_wish',
                                    'delay_first_wish',
                                    'delay_mind_sync',
                                    'delay_mind_sync',
                                    'delay_water_hesitation',
                                    'delay_water_hesitation',
                                    'delay_recruit_fear',
                                    'delay_commute_bag',
                                    'surplus_fons',
                                    'surplus_a_coin'],
              'esper_priority_ids': ['xiaozhi', 'edgar', 'nanali', 'hasuoer']}},
 {'id': 'discord_control',
  'name': '失谐空场',
  'short_name': '失谐',
  'description': '浊燃与黯星的进阶复合，压到对手空场后用高费异象道具取胜。',
  'difficulty': '高阶控制',
  'ai_nickname': '失谐控制 AI',
  'card_ids': ['murk_basic_material_box',
               'murk_basic_material_box',
               'murk_lost_whisper',
               'murk_lost_whisper',
               'murk_faded_shadow',
               'murk_faded_shadow',
               'murk_blur_number',
               'murk_fantasy_delusion',
               'murk_knight_spark',
               'darkstar_mining_permit',
               'darkstar_mining_permit',
               'darkstar_ringstone',
               'darkstar_ringstone',
               'darkstar_nature_pixel',
               'darkstar_oracle_stone',
               'darkstar_listening_crystal',
               'darkstar_someone_helmet',
               'discord_tomato',
               'discord_tomato_100',
               'discord_tomato_bucket'],
  'esper_card_ids': ['dafutier', 'fatiya', 'adler', 'requiem'],
  'ai_plan': {'priority_card_ids': ['murk_basic_material_box',
                                    'murk_basic_material_box',
                                    'murk_lost_whisper',
                                    'murk_lost_whisper',
                                    'murk_faded_shadow',
                                    'murk_faded_shadow',
                                    'murk_blur_number',
                                    'murk_fantasy_delusion',
                                    'murk_knight_spark',
                                    'darkstar_mining_permit',
                                    'darkstar_mining_permit',
                                    'darkstar_ringstone',
                                    'darkstar_ringstone',
                                    'darkstar_nature_pixel',
                                    'darkstar_oracle_stone',
                                    'darkstar_listening_crystal',
                                    'darkstar_someone_helmet',
                                    'discord_tomato',
                                    'discord_tomato_100',
                                    'discord_tomato_bucket'],
              'esper_priority_ids': ['adler', 'requiem', 'fatiya', 'dafutier']}}]
