from __future__ import annotations

from app.content.common.card_factory import _token
from app.content.common.constants import *

TOKEN_CARDS: dict[str, JsonDict] = {
    'material_fons': _token(
        'material_fons',
        '方斯',
        0,
        0,
        LUMINOUS_TOOL_ART,
        '灵属性素材。可被异能者登场吸收战力。',
        [TAG_MATERIAL, TAG_MAT_FONS],
    ),
    'material_coin': _token(
        'material_coin',
        '甲虫币',
        0,
        0,
        LUMINOUS_TOOL_ART,
        '光属性素材。可被异能者登场吸收战力。',
        [TAG_MATERIAL, TAG_MAT_COIN],
    ),
    'material_archive': _token(
        'material_archive',
        '猎人档案',
        0,
        0,
        ARCHIVE_TOOL_ART,
        '灵属性素材。可被异能者登场吸收战力。',
        [TAG_MATERIAL, TAG_MAT_ARCHIVE],
    ),
    'material_device': _token(
        'material_device',
        '器物模块',
        0,
        0,
        ARCHIVE_TOOL_ART,
        '相属性素材。可被异能者登场吸收战力。',
        [TAG_MATERIAL, TAG_MAT_DEVICE],
    ),
    'material_fire': _token(
        'material_fire',
        '异火石',
        0,
        0,
        CURSE_TOOL_ART,
        '咒属性素材。可被异能者登场吸收战力。',
        [TAG_MATERIAL, TAG_MAT_FIRE],
    ),
    'material_dust': _token(
        'material_dust',
        '混沌尘',
        0,
        0,
        CURSE_TOOL_ART,
        '暗属性素材。可被异能者登场吸收战力。',
        [TAG_MATERIAL, TAG_MAT_DUST],
    ),
    'material_oracle': _token(
        'material_oracle',
        '星辉残响',
        0,
        0,
        TIDE_TOOL_ART,
        '魂属性素材。可被异能者登场吸收战力。',
        [TAG_MATERIAL, TAG_MAT_ORACLE],
    ),
    'material_relic': _token(
        'material_relic',
        '旧刃残响',
        0,
        0,
        TIDE_TOOL_ART,
        '魂属性素材。可被异能者登场吸收战力。',
        [TAG_MATERIAL, TAG_MAT_RELIC],
    ),
    'material_signal': _token(
        'material_signal',
        '干扰信号',
        0,
        0,
        ARCHIVE_TOOL_ART,
        '相属性素材。可被异能者登场吸收战力。',
        [TAG_MATERIAL, TAG_MAT_SIGNAL],
    ),
    'harmony_genesis': _token(
        'harmony_genesis',
        '创生',
        0,
        0,
        LUMINOUS_TOOL_ART,
        '区域标记。每回合结束随机使一个己方单位 +1 战力；回合开始时自动减少 1 层。',
        [TAG_HARMONY, TAG_GENESIS],
    ),
    'harmony_murk': _token(
        'harmony_murk',
        '浊燃',
        0,
        0,
        CURSE_TOOL_ART,
        '区域标记。每回合结束使同区域一张对手单位 -1 战力，优先当前战力最高者；回合开始时自动减少 1 层。',
        [TAG_HARMONY, TAG_MURK],
    ),
    'harmony_delay': _token(
        'harmony_delay',
        '延滞',
        0,
        0,
        ARCHIVE_TOOL_ART,
        '区域标记。对手在该区域下一次部署额外需要 1 点能量，然后移除 1 层；回合开始时自动减少 1 层。',
        [TAG_HARMONY, TAG_DELAY],
    ),
    'harmony_surplus': _token(
        'harmony_surplus',
        '盈蓄',
        0,
        0,
        LUMINOUS_TOOL_ART,
        '融合标记。己方下次部署阶段生成 -1 费盈蓄牌；不占据格子。',
        [TAG_HARMONY, TAG_SURPLUS],
    ),
    'harmony_darkstar': _token(
        'harmony_darkstar',
        '黯星',
        0,
        0,
        TIDE_TOOL_ART,
        '区域标记。回合开始不减少层数；决胜回合结束时统一爆发，使同区域对手单位降低战力。',
        [TAG_HARMONY, TAG_DARKSTAR],
    ),
    'surplus_charge': _token(
        'surplus_charge',
        '盈蓄',
        -1,
        0,
        LUMINOUS_TOOL_ART,
        '-1 费 0 战力。揭示后消失，用于返还能量并继续展开。',
        [TAG_HARMONY, TAG_SURPLUS],
        'surplus_vanish',
    ),
    'muscle_plush': _token(
        'muscle_plush',
        '棉绒绒',
        0,
        3,
        LUMINOUS_TOOL_ART,
        '灵属性材料类别，3 战力衍生物。',
        [TAG_MATERIAL, TAG_MAT_FONS],
    ),
    'discordance': _token(
        'discordance',
        '失谐',
        0,
        0,
        CURSE_TOOL_ART,
        '区域标记。放大负面效果收益；不提供战力，不占据格子。',
        [TAG_HARMONY, TAG_DISCORD],
    ),
    'collapsing_card': _token(
        'collapsing_card',
        '倾陷中的卡牌',
        0,
        0,
        TIDE_TOOL_ART,
        '被黯星封存后的卡牌，只保留当前战力，不再拥有持续型效果。',
        [TAG_HARMONY, TAG_COLLAPSING],
    ),
}


__all__ = ['TOKEN_CARDS']
